### ISSUE TITLE
Create certificates for 2017

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/design#14]
It's that time of the year and we need to create certificates for the 2017 students. I'd basically go along with the design from last year to keep it uncomplicated, unless someone wants to create something new 😇

**Comment by campofino** [comment]
Just a question: would it make sense to keep the template in the G-Drive general folder?

Also, maybe, use the template also for coaches and supervisors who enquire about getting their work certified?

**Comment by alicetragedy** [comment]
Currently the template is in this folder/repo, since it's an inDesign file (as it contains graphics). I'm not sure if it's possible to add that into a Google Drive folder. For the coaches and supervisors I'd make it less complicated and just create a simple A4 document that confirms their participation?

**Comment by alicetragedy** [comment]
Just realised that didn't really answer your question @campofino, so:
- I think it's definitely useful to have something for coaches and supervisors as well, but I would do it as a pretty simple one-pager document with our letterhead. 
- I'd like to keep the “nice-looking” certificates for students only, and keep them in this format, since it's the best way to move items around within the certificate, add graphics and styling, etc. We can definitely duplicate having them in here and in the google drive, but I've never added non-drive-format files to a google drive folder before so I'm not sure how that would work.

**Comment by campofino** [comment]
Ok, that sounds great and makes a lot of sense.

**Comment by anasofiapinho** [comment]
@alicetragedy Is this a "help wanted" issue? When do you need the certificates? I can do this after we close the crowdfunding campaign if you want.

Re: files in google drive, you can just upload them there, but if you want to edit, you need to download them, just like we do here on GitHub.

**Comment by alicetragedy** [comment]
@anasofiapinho Right now I'd really like for us to focus on crowdfunding campaign, sponsorships, sharing blog posts of students, and the selection process, which is why it doesn't really have much priority. Can we re-discuss assigning this task after all the above is taken care of?

**Comment by alicetragedy** [comment]
Oh and to answer your question(s): I'd really love for you to take it on after if you don't have too much on your plate, and it's not really time-sensitive!

**Comment by anasofiapinho** [comment]
@alicetragedy sounds good! I'll get back to you after all of those things are finished.

**Comment by anasofiapinho** [comment]
@alicetragedy I have sent you the link to the drive where the certificates are. I have created a jpg version first with bigger resolution, and then a pdf version which for some strange reason has a lower resolution. There's also a version for print and another for web. I would send the files that are in the "JPG CMYK for Print" as people can use the jpg to post on social media if they want or send to a printshop to print the certificates.
All the files have the students names so that's easier for the person who is going to send them.

**Comment by anasofiapinho** [comment]
Hey @alicetragedy, the certificates are done! I also did 3 versions for some of the students as requested. I sent them to you. If everything is ok, we can close this.

**Comment by alicetragedy** [comment]
Awesome, thanks! Yes, let's close this. I'll tackle the sending separately.
