### ISSUE TITLE
Create Certificates for 2018

### ISSUE THREAD

**Issue by anasofiapinho** [rails-girls-summer-of-code/design#15]
- [x] ~Redesign to reflect 2018's colors~
- [x] Create certificates for each student in pdf (print quality, 300 dpi)
- [x] Send Certificates

**Comment by anasofiapinho** [comment]
Just adding here a note that I asked @alicetragedy to get me a list with the full name of the students so that I can start creating the certificates.

**Comment by alicetragedy** [comment]
@anasofiapinho it's unclear if you've started to work on this or not, but if you haven't, I'd like to pick this task up from you since I have a little bit of time this week. Let me know if I can un-assign you!

**Comment by anasofiapinho** [comment]
Hi again @alicetragedy! I finished the certificates and uploaded them to the RGSoC 2018 folder. I sent you the link. If everything is ok, we can close this issue.

**Comment by alicetragedy** [comment]
@anasofiapinho since the list in this issue also includes sending the certificates, maybe we can wait it out and close it when all the tasks broken down in here are done? 
I'll assign myself and remove you!

**Comment by alicetragedy** [comment]
@anasofiapinho has sent all of the certificates, so I'm closing this issue. Thanks Ana!
