### ISSUE TITLE
Rails Girls Summer of Code logo

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/design#2]
I already said, that I really don't like our "logo" as it is and I played around with it for 5 minutes. I think, we definitely can come up with something better than it is now.

this is now:

![screen shot 2015-02-26 at 12 15 38](https://cloud.githubusercontent.com/assets/1711357/6390941/38bd4b82-bdb1-11e4-8ce7-e41c0f6ba5a4.png)

and this is what i played around with:
1
![screen shot 2015-02-26 at 12 11 54](https://cloud.githubusercontent.com/assets/1711357/6390959/4aecba40-bdb1-11e4-921c-1cfaa5c07bb4.png)
2
![screen shot 2015-02-26 at 12 11 38](https://cloud.githubusercontent.com/assets/1711357/6390958/4aec83ea-bdb1-11e4-9673-0c52ad654a2e.png)
3
![screen shot 2015-02-26 at 12 11 33](https://cloud.githubusercontent.com/assets/1711357/6390960/4aedc8ea-bdb1-11e4-9788-c20c27b03fa0.png)

Just a beginning.. but I think we can do something with that? We could also play a lot around with the heart and see if it makes more sense on the left side or whatever. Who wants to help out with that? I think, I'd like to go with the Version 1 until we have something better.  wdyt, @apertoclaudi @alicetragedy ?

**Comment by ApertoClaudi** [comment]
Good 5-minutes-work, @anikalindtner ! ^^
I like the second one, because the font and heart are really good in balance here and  "rails girls" is already in focus. "Summer of code" is just a campaign, I think, that's why "RG" should stay in focus.

**Comment by anikalindtner** [comment]
@ApertoClaudi cool! thanks so much, will give it to @lislis to implement for now on the site, if no-one objects :D

**Comment by alicetragedy** [comment]
can we close this issue? I think Nr. 2 is everyone's choice and what we used for the stickers this year :)
Or do we want to keep it open for further discussion?

**Comment by sareg0** [comment]
I think we can close this.

On Sunday, 28 June 2015, Laura notifications@github.com wrote:

> can we close this issue? I think Nr. 2 is everyone's choice and what we
> used for the stickers this year :)
> Or do we want to keep it open for further discussion?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/design/issues/2#issuecomment-116294936
> .

## 

Kindest Regards,
Sara and the Rails Girls Summer of Code Team
@RailsGirlsSoC https://twitter.com/RailsGirlsSoC

Kindest Regards,
Sara
@sareg0 https://twitter.com/sareg0
+49(0)17699393251
