### ISSUE TITLE
Catch phrase and blurbs

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/design#3]
Even though ...
- RGSoC came out of Rails Girls, yes, but acutally, nowadays we're also open to other communities
- we do use Open Source projects, yes, but is Open Source actually is rather a means than main objective (which is diversity, and providing role model stories)

... our homepage now says:

![image](https://cloud.githubusercontent.com/assets/2208/6597652/5e443e18-c7fe-11e4-9c20-6e74273a4e07.png)

I think this can be optimized. Maybe we should use the terms "role model stories", "women", and "newcomers"

We now have:

> Get Rails Girls students into Open Source!
> With our fellowship program we aim to foster diversity in Open Source. Selected teams receive a three-month scholarship to work on Open Source projects of their choice.

How about

> Get more women into Open Source!
> Our fellowship program aims to foster diversity in tech by providing role model stories for programming newcomers. Selected teams receive a three-month scholarship to work on Open Source projects of their choice.

Thoughts?

Should we agree on this direction then we might also want to review other sections like the intro on the campaign page, and our general about page.

**Comment by lucaspinto** [comment]
If I may, I think you are absolutely right :)

**Comment by sareg0** [comment]
Totally. The feedback has been that we seem a little Rails/Rails Girls heavy/focused.

I'm always hesitant to use the word 'women', as we try to encourage applications from people socialized as female, but may not identify with the term 'woman'.

May be more like;
Let's open up Open Source!
#still a call to action word that identifies 'us' as in the community
Our fellowship program aims to foster diversity and create more female role models in open source. Selected teams receive a three-month scholarship to work on selected projects, to give them a kick-start in their technology careers.

It's defs not perfect, but I feel like it more accurately portrays that this could be a great launching platform for serious about making the next step to a career in programming.

**Comment by alicetragedy** [comment]
:+1: 

I like what has been said here so far and your draft, Sara. 
I understand the problematic "Women" but it's surely a step in the right direction (better than "Girls") :)

**Comment by sareg0** [comment]
Awesome, well we can update this thing this weekend if there are no objections
