### ISSUE TITLE
2015 Certificates for Participants

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/design#7]
Hey, we just closed up the 2014 issue on this, over in the 'orga' repo, but I think it's time to get started on them for this coming year... In the spirit of being super organised :)

One can find said certs in the design repo 
https://github.com/rails-girls-summer-of-code/design/tree/master/certificates

Perhaps @ApertoClaudi could do something up for us. @alicetragedy was our brilliant 2014 certificate designer, so she has a good idea of what needs to be included also :)

**Comment by ApertoClaudi** [comment]
Hey! Yes, that's a pretty one from the last year, so let's make a new one for this year! :smiley_cat: 
I will make up my mind and send you a few suggestions!

**Comment by alicetragedy** [comment]
@ApertoClaudi do you think you will have any time in the upcoming weeks to work on this? Last year we sent them very late, but I'd love to get this done before December, if possible. :heart:

**Comment by sareg0** [comment]
oh yes, that would be just so cool to have them out before the end of the year.

**Comment by ApertoClaudi** [comment]
Hey Sweathearts! :smile: Yeah, I will make them. Before december is a timing I can work with, I will find some time. :hourglass:

**Comment by sareg0** [comment]
many many thanks @ApertoClaudi!!

**Comment by alicetragedy** [comment]
that's so great @ApertoClaudi – thank you so much. please feel free to ping me if you need anything (help, feedback, brainstorming power, or cat gifs). :heart:

**Comment by ApertoClaudi** [comment]
Hihi, thank you @alicetragedy, that sounds very helpful, especially the cat gifs :D

**Comment by alicetragedy** [comment]
2015 certificates for participants have been created and sent. closing this :tada:
