### ISSUE TITLE
create header images for alumna blog posts

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/design#9]
We're currently working on a blog series where we present some of our alumna; for this, I thought it would be great to create small header images with a photo of the interviewee and the title of the series. 

Requirements and "copy":
- Time-sensitive — **needs doing in the next week**
- the header should be rectangular
- RGSoC logo
- Series title (ie. Alumna Series)
- interviewee full name
- interviewee picture (square or round)

The header could have a style similar to the [participant certificate](https://github.com/rails-girls-summer-of-code/design/blob/master/certificates/certificate_sample.pdf) or to the content we've been using on social media. 

Built on top of this, we could also, later on, get some great visual content for twitter and facebook (banners / images with quotes from the interviews).

**Comment by alicetragedy** [comment]
So @ApertoClaudi has offered to work on this <3

The names of the alumna we've interviewed so far:
- Oana Sipos
- Emma Koszinowski

As for the title, it's definitely not set in stone. I find "Alumna series" a little boring, so if anyone can come up with something better, I'd love that!!

This said, working with dummy content first is perfectly okay, we can figure the rest out later. 👍

**Comment by anasofiapinho** [comment]
Hey @ApertoClaudi

Great to see you are helping out with this! Thank you! <3

If you need anything from me, whether it's just brainstorming or feedback on other stuff, please feel free to ping me anytime. I tend to work at night, but I can get up early if necessary.

I would also like to say that we should probably create 2 images: one for the blog and a second one to share on social media.
The dimensions of the images for Twitter at the moment are 2:1, at least the part which is visible, because you can have a square image and Twitter won't show you the 1/4 top and the 1/4 bottom. On facebook they work best as a square. This means that we need to make an image that looks good if it is cut on the top and bottom, or at least have the picture of the person there and something which identifies RGSoC.

Images can't be more than 5 Mb and to save time I export to .png because that's the type of image facebook publishes. 

As @alicetragedy shared on the slack channel, I was thinking about creating an image with some questions and answers. We should review some of the most interesting questions and make a template we could use for other students. I am not in favor to put all the questions and answers there, because I believe we should create curiosity to drive traffic to our blog.

Ok, so these were just my thoughts! I want you to do whatever you feel like and I can't wait to see what you are doing! <3

**Comment by ApertoClaudi** [comment]
Hi @anasofiapinho! :) 

Thanks for all your input! If I need some more, I will ask you or send an owl into the night ;) 

I'm only a bit confused, if you want to put the whole interview in one picture? I thought like Laura mentioned, it's just a header visual? … If it's all in one, users cant's find it maybe via search engines. 

Anyway, I will work on it today and send you some layouts and suggestions. :)

**Comment by alicetragedy** [comment]
Hi @ApertoClaudi, just thought I'd reply to you quickly, so there are no misunderstanding. We have basically two different things here: one is the header image which I need for each alumna blog post (see this issue). That header image will probably need two or three formats: one for the blog post itself, and one for social media (either we use the same one for twitter and facebook, making sure it works well in both, or we create two separate ones, which is a little bit more work). 

The second thing we talked about in slack is a blog post "teaser", which imho is less important and less urgent, and which would have a couple of questions and answers for each students (basically something we can use to "push" each interview a little bit more after the initial share). I'd suggest creating a separate issue for this, so we don't confuse the two, and so we can post a couple of examples as inspiration.

**Comment by ApertoClaudi** [comment]
AAAAH! 💡 Now I get it. :D Thank you, @alicetragedy.

**Comment by ApertoClaudi** [comment]
So, here we go!

I made three versions for the headervisual. If we decide if its version v1, v2 or v3, than I will do the social media stuff and adapt it. 
I took the brilliant colors from @anasofiapinho Post it posts and made the picture of the interviewee square as well. I dind't find a cooler name for "alumna series" yet but I will think about it. 

And now: feedbacktiiime! 😸 

v1:
![blog-header-v1](https://cloud.githubusercontent.com/assets/7582849/15901653/73bc0480-2da4-11e6-95a4-27857764eb3c.jpg)

v2:
![blog-header-v2](https://cloud.githubusercontent.com/assets/7582849/15901655/73bfe1b8-2da4-11e6-8662-666f0a97d44f.jpg)

v3:
![blog-header-v3](https://cloud.githubusercontent.com/assets/7582849/15901654/73beee16-2da4-11e6-8118-97953290f29e.jpg)

PS: I will make the font in "alumna series" better in the final version. It's kind of _quick and dirty_ ;)

**Comment by alicetragedy** [comment]
awwwww yay @ApertoClaudi, thank you so much for this!!! ✨ 💖 

I think the first two versions are the ones that work best — my favourite favourite would have to be the second one, maybe because the text colour ("alumna series") blends in well with the background, and the logo looks better, placement-wise. 

If we decide not to go for 2, but for version 1 instead: I like it as well but I feel that our logo might look even better on there if it was aligned to the right side of the "interviewee image", what do you think?  

Other than that: LOVE THEM!!! 😍 thank you for your great work!

**Comment by anasofiapinho** [comment]
@ApertoClaudi This is AMAZING! Thank you! 💛 💚 💙 💜 💖

I couldn't do something like this! It would probably end up way boring and I wouldn't remember to use those colours.

I prefer v2, like Laura!

**Comment by anasofiapinho** [comment]
I really love this! So beautiful!

**Comment by ApertoClaudi** [comment]
Awww, thank you both for your feedback! 💖 If you could see my big fat smile... 😄 
I like v2 more, too, but I started with the first one and so I decided to share it with you as well.

@anasofiapinho: I was so in love with your Post it idea, i had to use all those pretty colours. And I think it is a very nice style for this years campaign. 😊 

So, I will adapt this header for Facebook and Twitter and share it with you by tomorrow.

**Comment by ApertoClaudi** [comment]
I rebrushed the template for the blog header and made two templates for twitter and facebook with a quote of the students. 
![blog-header-template](https://cloud.githubusercontent.com/assets/7582849/15937893/fcac642a-2e70-11e6-9831-a1c97b710ce6.png)

Facebook:
![alumna_series-facebook](https://cloud.githubusercontent.com/assets/7582849/15937891/fca52610-2e70-11e6-8716-99961c548410.jpg)

Twitter:
![alumna_series-twitter](https://cloud.githubusercontent.com/assets/7582849/15937892/fca854e8-2e70-11e6-97ee-64cf60999805.jpg)

@anasofiapinho : I found a cheat sheet for the different sizes: http://t3n.de/news/facebook-youtube-instagram-bilder-social-media-588552/social-media-cheat-sheet-bilder1/ So I used it for the social media images, but made the facebook visual half as big. 

Should I upload those templates then or do you give me quotes and pictures, @alicetragedy and I paste them in?

**Comment by alicetragedy** [comment]
@ApertoClaudi whooaaa, so beautiful 💖 
I'd say maybe you could upload the templates to the repo if it works with you? I think a version with some of the layers (like the background) flattened is totally fine, since we will not be making changes there. We will have this series run throughout the summer (and maybe beyond) so I don't know if you want to be pinged every time I need one for a new post. But it's up to you :)

**Comment by ApertoClaudi** [comment]
Thank you for your sparkling feedback, @alicetragedy! 😊 

I think, templates are definitely fine, so I made them ready to upload. But could you please be so kind and tell me, how it works here? Do I "create a new file" and upload the files then? I'm a GitHub noob, you know?! :D 🙈

**Comment by anasofiapinho** [comment]
WOW @ApertoClaudi ! <3 It's so beautiful! I am so happy you did this work!

Sorry for just seeing this now, I have been away all day.

**Comment by ApertoClaudi** [comment]
Thank you, Ana! 😊 And don't worry. ;)
